### ISSUE TITLE
Hi, does this extension make exe file from my kotlin code ?

### ISSUE THREAD

**Issue by vinodvinu** [fwcd/vscode-kotlin-ide#19]
Hi,
I am hobby programmer and would like to learn Kotlin. My area of interest is desktop applications in Windows. So i would like to know if this extension is able to to create an exe file for me ?

**Comment by fwcd** [comment]
Hi,

in general this is not possible (directly) using this extension.

This extension only provides language support (code completion, syntax highlighting, etc.), but no _build_ support. To _build_ your project into an executable file, you can either use the [Kotlin compiler](https://kotlinlang.org/docs/tutorials/command-line.html) directly or a build tool such as [Gradle](https://gradle.org/). Note that both of these have to be invoked from a command line (such as the integrated terminal in VSCode). You can check out https://github.com/fwcd/kotlin-quick-start for an example of what a Hello World with Gradle/Kotlin looks like. If you want to try it out, you just have to run the commands described in the README.

Note that the kotlin-quick-start project is using Kotlin/JVM. This means, you will get a `.jar` file instead of a `.exe`, since the code has to run on top of a Java Virtual Machine.

There is, however, also [Kotlin/Native](https://kotlinlang.org/docs/reference/native-overview.html), which compiles Kotlin code directly to a native binary (on Windows, "native binary" means an `exe` file). The extension only provides syntax highlighting for such projects currently though, proper Kotlin/Native support is a [planned feature](https://kotlinlang.org/docs/reference/native-overview.html).

**Comment by vinodvinu** [comment]
@fwcd ,
Thanks for the reply and links. Let me follow it. :)
