### ISSUE TITLE
Use "Kotlin" with "Kotlin Language" plugin? Or "Kotlin" replaces "Kotlin Language"?

### ISSUE THREAD

**Issue by trusktr** [fwcd/vscode-kotlin-ide#9]
Just curious, should I use both plugins? Or is "Kotlin" meant to provide the same as "Kotlin Language", and more?

**Comment by fwcd** [comment]
@trusktr You can think of "Kotlin" as being a superset of "Kotlin Language" since it not just provides syntax highlighting, but also other features, such as code completion or linting.

Thus you probably don't need both. I would recommed "Kotlin", but am somewhat biased towards my own project, so pick whatever you need. :)
